### ISSUE TITLE
Should find a way to test for the removal of \x00-type non-ASCI characters

### ISSUE THREAD

**Issue by LaChapeliere** [CRANE-toolbox/analysis-pipelines#15]
In test/test_preprocessing.py, test_remove_unicode()

**Comment by ccatterina** [comment]
Hi @LaChapeliere , here I am again.

Can I work on this?

**Comment by LaChapeliere** [comment]
Nice to see you back! :) For sure, please do! Is the issue clear enough?

**Comment by ccatterina** [comment]
Hi,
I thought that it was clear, but after looking at `remove_unicode` I'm not sure of what you are trying to achieve.

There are 2 things which seems a bit strange to me:
- The name `remove_unicode`, in python 3 `str` treats all characters as unicode points.
- The function `remove_unicode` tries to remove **escaped** unicode characters. Why do you expect to have escaped unicode characters here? Maybe it is a consequence of an other issue.

IMO if the goal is to filter out non-ascii characters we should rename the function and remove the part that replace escaped unicode characters. If the goal is only to filter out **escaped** unicode, probably the function should not exist.

Here you can find a really nice article about this topic: https://towardsdatascience.com/a-guide-to-unicode-utf-8-and-strings-in-python-757a232db95c

**Comment by LaChapeliere** [comment]
Thank you for the link, it made things much clearer for me because, to be honest, I hadn't given it much thought.

After going back to the research paper we used to select our preprocessing steps, I realise I had misunderstood the goal of the remove_unicode function. It is supposed to both of the options you mentionned:
- Remove non-ascii characters
- Remove escaped unicode (which might appear because of the way the data was collected)

Do you think there should be two functions? The current one only does the second step, am I right? Or it's not even doing that?

**Comment by ccatterina** [comment]
Oh ok, thank you for the explanation.

Actually the function already does both the steps. For the sake of clarity, I would split the function in 2 functions called `remove_escaped_unicode` and `remove_non_ascii`. What do you think?

**Comment by LaChapeliere** [comment]
Yes, it would be much clearer and avoid additional confusion of users that aren't too familiar with unicode treatement in Python like me!
Do you want to take charge of this updated issue?

**Comment by ccatterina** [comment]
Sure, I'll send a PR tomorrow!

**Comment by LaChapeliere** [comment]
@ccatterina Thank you very much for figuring this one out!
