### ISSUE TITLE
Deal with ordinal numbers in preprocessing

### ISSUE THREAD

**Issue by LaChapeliere** [CRANE-toolbox/analysis-pipelines#17]
In src/preprocess/preprocessTools.py, replace_numbers
The num2words package can replace by ordinal number but it needs to be specified, so we need to detect when a number is ordinal.
Ex: "2nd" -> "2" + "nd" -> "2" + ordinal -> num2words(2, ordinal)
Appropriate unit testing must also be added

**Comment by ccatterina** [comment]
Hi, is it okay if I work on this? Really nice project anyway!

**Comment by LaChapeliere** [comment]
Sure, thank you for contributing!
My issues' descriptions are rather lacking, I'm working on adding an issue template, so let me know if you need additional info.

**Comment by ccatterina** [comment]
No thanks, it's seems pretty clear. I will create a PR as soon as possible.

**Comment by ccatterina** [comment]
Oh, sorry, I have a question instead :grin: . How do you run the testsuite?

Is there something like:
```sh
python -m unittest discover tests/
```
to run all the tests? Or you run the single test manually when you change something?

**Comment by LaChapeliere** [comment]
We are using pytest, which is why you couldn't make unittest work. We forgot to document that :facepalm: 
So you'll need to install it for python3 then run `python3 -m pytest` at the root of the package.

**Comment by ccatterina** [comment]
Thank you for the clarification.

`pytest` could be added to the `Pipfile` dev dependencies, what do you think?

**Comment by LaChapeliere** [comment]
It should, clearly! I think there was a reason we didn't while working with testPypi, but we should be able to do it now.

**Comment by LaChapeliere** [comment]
Thanks a lot @ccatterina ! :love_letter:
