### ISSUE TITLE
Recognise all contributors

### ISSUE THREAD

**Issue by LaChapeliere** [CRANE-toolbox/analysis-pipelines#47]
Add a contributors table in the Readme using the CLI tool from https://github.com/all-contributors/all-contributors

**Comment by LaChapeliere** [comment]
@all-contributors please add @LaChapeliere for code, tests, doc, ideas, maintenance, project management

**Comment by LaChapeliere** [comment]
@all-contributors please add @IanSaucy for code, tests, doc, ideas, infra, project management, review

**Comment by LaChapeliere** [comment]
@all-contributors please add @SvetlanaMoldavskaya for content, doc, design, user testing, ideas

**Comment by LaChapeliere** [comment]
@all-contributors please add @MarkoShiva for code
@all-contributors please add @ccatterina for code, tests
@all-contributors please add @paulmhan for code

**Comment by LaChapeliere** [comment]
@all-contributors please add @gianlucasb for data, ideas

**Comment by LaChapeliere** [comment]
@all-contributors please add @MarkoShiva for code

**Comment by LaChapeliere** [comment]
@all-contributors please add @ccatterina for code, tests

**Comment by LaChapeliere** [comment]
@all-contributors please add @paulmhan for code

**Comment by LaChapeliere** [comment]
@all-contributors please add @lykelly19 for code, ideas, bug

**Comment by LaChapeliere** [comment]
@all-contributors please add Rachael Dier for design, content, user testing, ideas

**Comment by LaChapeliere** [comment]
Oops, can't add people who don't have a github account

**Comment by MarkoShiva** [comment]
Why?

**Comment by MarkoShiva** [comment]
What is the point of spamming with those merge requests?

**Comment by LaChapeliere** [comment]
@MarkoShiva Would you like me to remove you from the contributors table?
Else, I know the all-contributors-bot isn't perfect and creates too many PRs, but I didn't code it and I'm happy to use it, so I'm not going to complain about it.
You know that you can unsuscribe from a repo, right?

**Comment by LaChapeliere** [comment]
@all-contributors please add @riibeirogabriel for code

**Comment by LaChapeliere** [comment]
@all-contributors please add @riibeirogabriel for code

**Comment by LaChapeliere** [comment]
@all-contributors please add @riibeirogabriel for code

**Comment by LaChapeliere** [comment]
@all-contributors please add @WorkInProgress-Development for doc

**Comment by LaChapeliere** [comment]
@all-contributors please add @tomasloksa for code, doc

**Comment by LaChapeliere** [comment]
@all-contributors please add @tomasloksa for code, doc
