### ISSUE TITLE
Fix broken links to Contributing section in FAQ

### ISSUE THREAD

**Issue by LaChapeliere** [CRANE-toolbox/analysis-pipelines#48]
README.md
The links to the Contributing section from the various FAQ questions are broken.
All `##Contributing` links in the FAQ should be replaced by `#contributing`. Be careful not to carelessly Replace All, that would remove the section header.

**Comment by paulmhan** [comment]
Can I take this?

**Comment by LaChapeliere** [comment]
Sure! Feel free to ask questions if anything is unclear, but this one should be a straightforward PR

**Comment by paulmhan** [comment]
So this is the first time I'm trying to contribute to open source, when I tried to push, I get a message saying "remote: Permission to CRANE-toolbox/analysis-pipelines.git denied to paulmhan."

Is this something on my end?

**Comment by LaChapeliere** [comment]
This repository (and most open source projects) is set up so that only contributors that the admins add to the team can push directly to the repo. You need to do a "fork" and push from there.
I did the exact same mistake a few hours ago because I've only ever pushed to repos I was a collaborator of before ;) This website gave me an easy way to fix the problem (just skip the long introduction): http://thebillwagner.com/blog/Item/2015-08-18-IforgottoforkbeforeIstartedworkingandhowtofixit
Don't hesitate to ask if the tutorial isn't clear to you!

**Comment by paulmhan** [comment]
Thank you so much!
