### ISSUE TITLE
Add Back to top links to Readme

### ISSUE THREAD

**Issue by LaChapeliere** [CRANE-toolbox/analysis-pipelines#61]
To help users navigate, add [Back to top](#crisis-racism-and-narrative-evaluation) after each level 2 header (except for Table of Content) in README.md

**Comment by WorkInProgress-Development** [comment]
Can I do this?
(Sorry if I've worded this badly, somewhat unfamiliar with taking random issues I find)

**Comment by LaChapeliere** [comment]
You're welcome to work on it :) And I don't see any issue with your wording

**Comment by WorkInProgress-Development** [comment]
Can I confirm, when you say 'after each level 2 header', do you mean like 
![image](https://user-images.githubusercontent.com/38821590/95190675-6b2a3700-081b-11eb-9479-c3c8a3842674.png) (example A)
or do you mean at the end of each section, just before there is a level 2 header, e.g. 
![image](https://user-images.githubusercontent.com/38821590/95190908-b5131d00-081b-11eb-81a8-33e121108f64.png).
(By the way, my text editor is using a different markdown css :))

**Comment by LaChapeliere** [comment]
The first option please!

**Comment by WorkInProgress-Development** [comment]
If it's okay, I'd like to also make a PR with a couple of spelling and grammar errors I found whilst reading the readme? I know often small-ish pull requests like these are annoying, so I'd like to check before I do anything (and yes, it will be just one pr with multiple commits)
