### ISSUE TITLE
Add shields to the readme

### ISSUE THREAD

**Issue by LaChapeliere** [CRANE-toolbox/analysis-pipelines#67]
Add License, Version (Pypi), Activity (Github last commit) and Issue tracking (Number of open "help wanted" issues) shields next to the number of contributors in README.md
https://shields.io/

**Comment by tomasloksa** [comment]
I got this 😊

**Comment by LaChapeliere** [comment]
@tomasloksa It looks like there's a parasite link added when using the bot: https://github.com/CRANE-toolbox/analysis-pipelines/tree/all-contributors/add-tomasloksa

**Comment by tomasloksa** [comment]
That's weird... Could you somehow disable adding the badge in the bot settings? (If there are any..., I'm on the phone right now and can't look into it) The shield I had in the first commit was working even without the bot.

**Comment by LaChapeliere** [comment]
I can't disable it but here's a parameter in the bot config file that is listed as "Define your own lodash template to generate the badge."
I think the solution you found in the issues uses the old code for the bot, as I found this FAQ question: https://allcontributors.org/docs/en/bot/faq

**Comment by LaChapeliere** [comment]
Works perfectly, thank you so much @tomasloksa !
