### ISSUE TITLE
Fix setup method for Windows users

### ISSUE THREAD

**Issue by LaChapeliere** [CRANE-toolbox/analysis-pipelines#77]
So I think is due to how the path is being built [here](https://github.com/CRANE-toolbox/analysis-pipelines/blob/a142200d53d955d5313f69308011bc01e443329a/setup.py#L6). This method would work for most *nix systems but probably fails on windows since windows uses a `\` not a `/` for paths. 

We should change the method in the `setup.py` to use [`os.path.join`](https://docs.python.org/3/library/os.path.html#os.path.join). 

I think this should fix the issue but I have not tested.

_Originally posted by @IanSaucy in https://github.com/CRANE-toolbox/analysis-pipelines/issues/24#issuecomment-727265409_

**Comment by LaChapeliere** [comment]
@riibeirogabriel If I make the change, would you be able to test it? (Since I don't have a Windows computer around)

**Comment by riibeirogabriel** [comment]
Yes, make the changes and i will notify you and then continue with this
issue, thanks!

**Comment by LaChapeliere** [comment]
@riibeirogabriel You should be able to install the TestPyPi version: https://test.pypi.org/project/cranetoolbox/
with `pip install -i https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple cranetoolbox`
Tell me if it works so I can publish to the main PyPi :)

**Comment by riibeirogabriel** [comment]
Yes, it works on my windows machine, but it will works when try installing the package locally?

**Comment by IanSaucy** [comment]
@riibeirogabriel In theory it should! But feel free to pull down this branch and give it a manual test. What was deployed to `test.pypi` is exactly what is in this branch.

**Comment by riibeirogabriel** [comment]
Okay, where is the branch to make the local test?

**Comment by IanSaucy** [comment]
Ah oops, I assumed it had been pushed up. Once @LaChapeliere pushes things into a branch you should be able to pull.

**Comment by LaChapeliere** [comment]
@riibeirogabriel I just pushed on branch `fix-setup-windows` so you can test the local editable install.

**Comment by riibeirogabriel** [comment]
In branch also works!
